language: node_js
node_js:
  - 12
script:
  - eslint 'src/**'
  - npm run test:coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: main